export function getContainChars(input: string): string[] {
  const result: string[] = [];
  if (input.includes("ア")) { result.push("あ"); }
  if (input.includes("イ")) { result.push("い"); }
  if (input.includes("ウ")) { result.push("う"); }
  if (input.includes("エ")) { result.push("え"); }
  if (input.includes("オ")) { result.push("お"); }
  if (input.includes("カ")) { result.push("か"); }
  if (input.includes("キ")) { result.push("き"); }
  if (input.includes("ク")) { result.push("く"); }
  if (input.includes("ケ")) { result.push("け"); }
  if (input.includes("コ")) { result.push("こ"); }
  if (input.includes("サ")) { result.push("さ"); }
  if (input.includes("シ")) { result.push("し"); }
  if (input.includes("ス")) { result.push("す"); }
  if (input.includes("セ")) { result.push("せ"); }
  if (input.includes("ソ")) { result.push("そ"); }
  if (input.includes("タ")) { result.push("た"); }
  if (input.includes("チ")) { result.push("ち"); }
  if (input.includes("ツ")) { result.push("つ"); }
  if (input.includes("テ")) { result.push("て"); }
  if (input.includes("ト")) { result.push("と"); }
  if (input.includes("ナ")) { result.push("な"); }
  if (input.includes("ニ")) { result.push("に"); }
  if (input.includes("ヌ")) { result.push("ぬ"); }
  if (input.includes("ネ")) { result.push("ね"); }
  if (input.includes("ノ")) { result.push("の"); }
  if (input.includes("ハ")) { result.push("は"); }
  if (input.includes("ヒ")) { result.push("ひ"); }
  if (input.includes("フ")) { result.push("ふ"); }
  if (input.includes("ヘ")) { result.push("へ"); }
  if (input.includes("ホ")) { result.push("ほ"); }
  if (input.includes("マ")) { result.push("ま"); }
  if (input.includes("ミ")) { result.push("み"); }
  if (input.includes("ム")) { result.push("む"); }
  if (input.includes("メ")) { result.push("め"); }
  if (input.includes("モ")) { result.push("も"); }
  if (input.includes("ヤ")) { result.push("や"); }
  if (input.includes("ユ")) { result.push("ゆ"); }
  if (input.includes("ヨ")) { result.push("よ"); }
  if (input.includes("ラ")) { result.push("ら"); }
  if (input.includes("リ")) { result.push("り"); }
  if (input.includes("ル")) { result.push("る"); }
  if (input.includes("レ")) { result.push("れ"); }
  if (input.includes("ロ")) { result.push("ろ"); }
  if (input.includes("ワ")) { result.push("わ"); }
  if (input.includes("ン")) { result.push("ん"); }
  if (input.includes("ヴ")) { result.push("う"); }
  if (input.includes("ガ")) { result.push("か"); }
  if (input.includes("ギ")) { result.push("き"); }
  if (input.includes("グ")) { result.push("く"); }
  if (input.includes("ゲ")) { result.push("け"); }
  if (input.includes("ゴ")) { result.push("こ"); }
  if (input.includes("ザ")) { result.push("さ"); }
  if (input.includes("ジ")) { result.push("し"); }
  if (input.includes("ズ")) { result.push("す"); }
  if (input.includes("ゼ")) { result.push("せ"); }
  if (input.includes("ゾ")) { result.push("そ"); }
  if (input.includes("ダ")) { result.push("た"); }
  if (input.includes("ヂ")) { result.push("ち"); }
  if (input.includes("ヅ")) { result.push("つ"); }
  if (input.includes("デ")) { result.push("て"); }
  if (input.includes("ド")) { result.push("と"); }
  if (input.includes("バ")) { result.push("は"); }
  if (input.includes("ビ")) { result.push("ひ"); }
  if (input.includes("ブ")) { result.push("ふ"); }
  if (input.includes("ベ")) { result.push("へ"); }
  if (input.includes("ボ")) { result.push("ほ"); }
  if (input.includes("パ")) { result.push("は"); }
  if (input.includes("ピ")) { result.push("ひ"); }
  if (input.includes("プ")) { result.push("ふ"); }
  if (input.includes("ペ")) { result.push("へ"); }
  if (input.includes("ポ")) { result.push("ほ"); }
  return result;
}