name: CI

on:
  push:
    branches:    # Array of patterns that match refs/heads
    - master     # Push events on master branch


jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@master
      with:
        node-version: 10.x 
    - run: npm install && npm run build && cp ./dist .. && ls -lav ..
    - run: pwd
    - run: df -h
    - run: git config --list
    - run: mkdir ../gh-pages/ && cd ../gh-pages/ && git clone git@github.com:${GITHUB_REPOSITORY}
    - run: cwd
